apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arp-pvc
  namespace: arp-system
  labels:
    app.kubernetes.io/name: arp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
