apiVersion: v1
kind: Service
metadata:
  name: arp-dashboard
  namespace: arp-system
  labels:
    app.kubernetes.io/name: arp
    app.kubernetes.io/component: dashboard
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: arp
    app.kubernetes.io/component: dashboard
